import { CircleHelp, Info, Smartphone } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';

import { Container } from '@/components/layout/container';
import { CsrfField } from '@/components/security/csrf-field';
import { OperatorMark } from '@/components/pay/operator-mark';
import { CIRCLES, OPERATORS, PLANS_BY_OPERATOR, RECHARGE_PLANS } from '@/data/recharge-plans';
import { getSession } from '@/lib/auth/guards';
import { formatPaise, rupeesToPaise } from '@/lib/utils/money';
import { listRecharges } from '@/services/recharge';
import { getWalletSummary } from '@/services/wallet';

import { RechargeForm } from './recharge-form';

export const metadata: Metadata = {
  title: 'Mobile Recharge',
  description: 'Prepaid mobile recharge, paid from your Eshwaran Pay balance.',
};

export const dynamic = 'force-dynamic';

/**
 * Prepaid mobile recharge.
 *
 * Built to the reference: enter a number, confirm the operator and circle,
 * open the plan sheet, pay. All of it works -- the number is validated against
 * the real Indian format, the plan price is read on the server, the wallet is
 * debited into the same ledger everything else in this store uses, and the
 * recharge is recorded and listed.
 *
 * **The operators are the four real networks; the plans are not their plans.**
 * Every price, allowance and validity in the sheet is generated by this project.
 * That distinction is the one thing on this page a customer could be misled
 * about, so it is stated above the plan sheet rather than in small print — a
 * page that takes money against a price has to be clear where the price came
 * from. The marks beside each name are original geometry, not the networks'
 * logos.
 *
 * The telecom circles *are* real: India's prepaid market genuinely is divided
 * into those twenty-two licensed service areas.
 */
export default async function RechargePage() {
  const session = await getSession();

  const [summary, history] = await Promise.all([
    session
      ? getWalletSummary(session.user.id)
      : Promise.resolve({ balance: 0, wallet: 0, giftCards: 0, pending: 0 }),
    session ? listRecharges(session.user.id, 5) : Promise.resolve([]),
  ]);

  return (
    <Container size="narrow" className="space-y-4 py-5 sm:py-7">
      <nav aria-label="Breadcrumb" className="text-ink-muted text-sm">
        <Link href="/pay" className="hover:text-link hover:underline">
          Eshwaran Pay
        </Link>
        <span className="mx-1.5" aria-hidden="true">
          ›
        </span>
        <span className="text-ink">Mobile Recharge</span>
      </nav>

      <div className="flex items-end justify-between gap-3">
        <h1 className="flex items-center gap-2 text-xl font-bold sm:text-2xl">
          <Smartphone className="text-accent-400 h-5 w-5" aria-hidden="true" />
          Mobile Recharge
        </h1>
        <p className="text-ink-muted shrink-0 text-sm">
          Balance <span className="text-accent-400 font-bold">{formatPaise(summary.balance)}</span>
        </p>
      </div>

      <RechargeForm
        operators={OPERATORS.map((operator) => ({
          id: operator.id,
          name: operator.name,
          short: operator.short,
          tone: operator.tone,
          colour: operator.colour,
          tagline: operator.tagline,
        }))}
        circles={[...CIRCLES]}
        plans={RECHARGE_PLANS.map((plan) => ({
          id: plan.id,
          operatorId: plan.operatorId,
          rupees: plan.rupees,
          paise: rupeesToPaise(plan.rupees),
          data: plan.data,
          validity: plan.validity,
          calls: plan.calls,
          sms: plan.sms,
          benefits: [...plan.benefits],
          tabs: [...plan.tabs],
        }))}
        balance={summary.balance}
        signedIn={Boolean(session)}
        csrfField={<CsrfField />}
      />

      {/* ------------------------------------------------ operators we carry */}
      <section
        aria-labelledby="recharge-operators"
        className="border-hairline bg-surface rounded-2xl border p-4"
      >
        <h2 id="recharge-operators" className="text-sm font-bold">
          Networks
        </h2>
        <ul className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">
          {OPERATORS.map((operator) => (
            <li
              key={operator.id}
              className="border-hairline bg-surface-sunken flex flex-col items-center gap-2 rounded-xl border p-3 text-center"
            >
              <OperatorMark
                operatorId={operator.id}
                colour={operator.colour}
                name={operator.name}
                size={30}
              />
              <span className="text-ink-muted block text-[11px] leading-tight">
                {operator.tagline}
              </span>
              <span className="text-ink-subtle block text-[10px]">
                {PLANS_BY_OPERATOR[operator.id]?.length ?? 0} plans
              </span>
            </li>
          ))}
        </ul>
      </section>

      {/* ------------------------------------------------- zero fees strip */}
      <section className="rounded-2xl bg-gradient-to-r from-amber-400 to-amber-300 p-4 text-amber-950">
        <p className="text-lg leading-tight font-black">
          Zero platform fee <span className="font-bold">on every recharge</span>
        </p>
        <p className="mt-1 text-sm">
          The amount you pick is the amount that leaves your balance — no convenience charge, no
          processing fee.
        </p>
      </section>

      {/* --------------------------------------------------- past recharges */}
      {history.length > 0 && (
        <section
          aria-labelledby="recharge-history"
          className="border-hairline bg-surface overflow-hidden rounded-2xl border"
        >
          <h2
            id="recharge-history"
            className="border-hairline border-b px-4 py-3 text-sm font-bold"
          >
            Recent recharges
          </h2>
          <ul className="divide-hairline divide-y">
            {history.map((entry) => (
              <li key={entry.id} className="flex items-start justify-between gap-3 px-4 py-3">
                <span className="min-w-0">
                  <span className="block text-sm font-semibold">{entry.mobile}</span>
                  <span className="text-ink-muted block text-xs">
                    {entry.operatorName}
                    {entry.circle ? `, ${entry.circle}` : ''}
                  </span>
                  <span className="text-ink-subtle block font-mono text-[11px]">
                    {entry.reference}
                  </span>
                </span>
                <span className="shrink-0 text-right">
                  <span className="block text-sm font-semibold">{formatPaise(entry.amount)}</span>
                  <span className="text-ink-subtle block text-[11px]">
                    {entry.createdAt.toLocaleDateString('en-IN', {
                      day: 'numeric',
                      month: 'short',
                    })}
                  </span>
                </span>
              </li>
            ))}
          </ul>
        </section>
      )}

      <p className="text-ink-subtle flex items-start gap-2 text-xs leading-relaxed">
        <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden="true" />
        <span>
          <strong className="text-ink">These are not the operators&apos; real plans.</strong> Every
          price, allowance and validity below is made up by this store — check the network&apos;s
          own app or site before you rely on any of it, and note that no recharge here reaches a
          real phone. The circles are the twenty-two licensed service areas India actually uses, and
          the operator shown for a number is derived from the number rather than looked up, so
          correct it if it is wrong. What is real is the money: the plan price is read on the server
          and debited from your{' '}
          <Link href="/pay/balance" className="text-link hover:underline">
            Eshwaran Pay balance
          </Link>
          .
        </span>
      </p>

      <p className="text-center">
        <Link
          href="/help"
          className="text-link inline-flex items-center gap-1.5 text-sm font-semibold hover:underline"
        >
          <CircleHelp className="h-4 w-4" aria-hidden="true" />
          Help &amp; FAQs
        </Link>
      </p>
    </Container>
  );
}
