/**
 * Prepaid mobile recharge: operators, circles and tariff books.
 *
 * **The operators are the four real Indian networks, and the plans are not.**
 * Every price, allowance and validity below is generated by this project -- none
 * of it is any network's published tariff, and none of it should be read as one.
 * The recharge page says so above the plan sheet rather than in small print,
 * because a page that takes money against a price needs to be clear about where
 * that price came from.
 *
 * Nothing here reproduces a network's logo either: the marks in
 * `components/pay/operator-mark.tsx` are original geometry, and the colours are
 * there to tell four chips apart in a row rather than to stand in for a brand.
 *
 * **The telecom circles are real.** India's prepaid market genuinely is divided
 * into the twenty-two licensed service areas listed here, and tariffs really
 * are priced per circle. That part is public fact and worth being right about.
 *
 * **The plans are generated, not typed out.** Forty per operator, composed from
 * each operator's own price ladder and benefit pool by a seeded PRNG -- the
 * same technique `data/catalog.ts` uses for the product catalogue, for the same
 * reason: 160 hand-written entries would drift, and a deterministic generator
 * gives every machine the same book.
 */

export interface OperatorTariff {
  /** Daily-data packs: the spine of any Indian prepaid sheet. */
  dailyData: string[];
  /** 28-day price points. Longer packs are derived from these. */
  basePrices: number[];
  /** Extras this operator bundles, drawn from deterministically. */
  perks: string[];
  /** Data-only top-up sizes. */
  topUpData: string[];
}

export interface Operator {
  id: string;
  name: string;
  short: string;
  /** Tailwind classes for the operator chip. */
  tone: string;
  /** Brand colour for the generated mark. */
  colour: string;
  tagline: string;
  tariff: OperatorTariff;
}

export const OPERATORS: readonly Operator[] = [
  {
    id: 'jio',
    name: 'Jio',
    short: 'JIO',
    tone: 'bg-blue-700 text-white',
    colour: '#1d4ed8',
    // Descriptive of this store's plan book for the operator, not a claim about
    // the network -- "fastest" or "widest coverage" would be one.
    tagline: 'Daily data packs',
    tariff: {
      dailyData: ['1 GB/day', '1.5 GB/day', '2 GB/day', '2.5 GB/day', '3 GB/day'],
      basePrices: [199, 239, 269, 299, 349, 399, 449],
      perks: [
        'Unlimited 5G',
        'Prime Video included',
        'Weekend data rollover',
        'Caller tunes',
        'Free night data',
      ],
      topUpData: ['1 GB', '2 GB', '5 GB', '10 GB', '30 GB'],
    },
  },
  {
    id: 'airtel',
    name: 'Airtel',
    short: 'AIR',
    tone: 'bg-red-600 text-white',
    colour: '#dc2626',
    tagline: 'Unlimited calling packs',
    tariff: {
      dailyData: ['1 GB/day', '1.5 GB/day', '2 GB/day', '2.5 GB/day'],
      basePrices: [179, 209, 249, 289, 319, 379, 429],
      perks: [
        'Unlimited 5G',
        'Spam call alerts',
        'Music streaming',
        'Prime Video included',
        'Device protection',
      ],
      topUpData: ['1 GB', '3 GB', '6 GB', '15 GB', '25 GB'],
    },
  },
  {
    id: 'bsnl',
    name: 'BSNL',
    short: 'BSNL',
    tone: 'bg-amber-500 text-amber-950',
    colour: '#f59e0b',
    tagline: 'Long validity packs',
    tariff: {
      dailyData: ['1 GB/day', '1.5 GB/day', '2 GB/day'],
      basePrices: [149, 189, 219, 259, 299, 339, 389],
      perks: [
        'Unlimited 5G',
        'Free national roaming',
        'Cricket pass',
        'Cloud backup',
        'Extra talktime',
      ],
      topUpData: ['1 GB', '2 GB', '4 GB', '12 GB', '20 GB'],
    },
  },
  {
    id: 'vi',
    name: 'Vi',
    short: 'VI',
    tone: 'bg-violet-600 text-white',
    colour: '#7c3aed',
    tagline: 'Data-heavy packs',
    tariff: {
      dailyData: ['1.5 GB/day', '2 GB/day', '2.5 GB/day', '3 GB/day', '4 GB/day'],
      basePrices: [209, 259, 289, 329, 369, 419, 479],
      perks: [
        'Unlimited 5G',
        'Data rollover',
        'Gaming pass',
        'Prime Video included',
        'Hotspot included',
      ],
      topUpData: ['2 GB', '5 GB', '10 GB', '20 GB', '50 GB'],
    },
  },
];

/** The twenty-two licensed service areas. Real, and the unit tariffs are set in. */
export const CIRCLES: readonly string[] = [
  'Andhra Pradesh',
  'Assam',
  'Bihar & Jharkhand',
  'Chennai',
  'Delhi NCR',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu & Kashmir',
  'Karnataka',
  'Kerala',
  'Kolkata',
  'Madhya Pradesh & Chhattisgarh',
  'Maharashtra & Goa',
  'Mumbai',
  'North East',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Tamil Nadu',
  'Uttar Pradesh (East)',
  'West Bengal',
];

export const PLAN_TABS = [
  'Popular',
  'Unlimited 5G',
  'Data',
  'Entertainment',
  'Gaming',
  'Top-up',
] as const;

export type PlanTab = (typeof PLAN_TABS)[number];

export interface RechargePlan {
  id: string;
  operatorId: string;
  /** Rupees. Converted to paise at the edge, like the rest of the catalogue. */
  rupees: number;
  data: string;
  /** Days, or null for a pack that rides on the existing validity. */
  validityDays: number | null;
  validity: string;
  calls: string;
  sms: string;
  benefits: string[];
  tabs: PlanTab[];
}

// ---------------------------------------------------------------- generation

/** FNV-1a, matching the rest of the project's deterministic generators. */
function hash(value: string): number {
  let h = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    h ^= value.charCodeAt(index);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/** mulberry32 -- small, fast, seedable. No `Math.random()` anywhere. */
function makeRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick<T>(items: readonly T[], random: () => number): T {
  const item = items[Math.floor(random() * items.length) % items.length];
  if (item === undefined) throw new Error('pick: empty list');
  return item;
}

/** Longer packs cost less per day, which is the whole point of buying one. */
const TERMS: Array<{ days: number; label: string; multiplier: number }> = [
  { days: 28, label: '28 days', multiplier: 1 },
  { days: 56, label: '56 days', multiplier: 1.85 },
  { days: 84, label: '84 days', multiplier: 2.6 },
  { days: 365, label: '365 days', multiplier: 9.5 },
];

const PLANS_PER_OPERATOR = 40;

/**
 * One operator's book of forty.
 *
 * The mix mirrors a real prepaid sheet: unlimited packs across four terms, then
 * data top-ups that do not extend validity, entertainment and gaming add-ons,
 * and plain talktime. Prices are rounded to a rupee and made unique within the
 * operator, because two plans at the same price in the same list is the kind of
 * thing that reads as filler.
 */
function generatePlans(operator: Operator): RechargePlan[] {
  const random = makeRandom(hash(`recharge:${operator.id}`));
  const { dailyData, basePrices, perks, topUpData } = operator.tariff;
  const plans: RechargePlan[] = [];
  const takenPrices = new Set<number>();

  const priceFor = (base: number, multiplier: number): number => {
    let rupees = Math.round(base * multiplier);
    // Nudge upward until unique: a duplicate price with different contents is
    // indistinguishable to a shopper scanning a column of amounts.
    while (takenPrices.has(rupees)) rupees += 1;
    takenPrices.add(rupees);
    return rupees;
  };

  const add = (plan: Omit<RechargePlan, 'id' | 'operatorId'>): void => {
    plans.push({ ...plan, id: `${operator.id}-${plans.length + 1}`, operatorId: operator.id });
  };

  // ---- unlimited packs: every daily allowance across every term ----------
  for (const term of TERMS) {
    for (const data of dailyData) {
      if (plans.length >= 28) break;
      const base = pick(basePrices, random);
      const benefits = [perks[0] ?? 'Unlimited 5G'];
      if (random() > 0.55) benefits.push(pick(perks.slice(1), random));

      const tabs: PlanTab[] = ['Unlimited 5G'];
      if (term.days <= 56) tabs.push('Popular');
      if (benefits.some((benefit) => benefit.includes('Prime Video'))) tabs.push('Entertainment');
      if (benefits.some((benefit) => benefit.includes('Gaming'))) tabs.push('Gaming');

      add({
        rupees: priceFor(base, term.multiplier),
        data,
        validityDays: term.days,
        validity: term.label,
        calls: 'Unlimited',
        sms: '100/day',
        benefits,
        tabs,
      });
    }
  }

  // ---- data top-ups: no validity of their own ----------------------------
  for (const data of topUpData) {
    add({
      rupees: priceFor(19 + Math.floor(random() * 180), 1),
      data,
      validityDays: null,
      validity: 'Existing plan',
      calls: 'NA',
      sms: 'NA',
      benefits: ['Rides on your current validity'],
      tabs: ['Data', 'Top-up'],
    });
  }

  // ---- data packs with their own validity --------------------------------
  for (const days of [7, 30, 56]) {
    add({
      rupees: priceFor(49 + Math.floor(random() * 200), 1),
      data: pick(topUpData, random),
      validityDays: days,
      validity: `${days} days`,
      calls: 'NA',
      sms: 'NA',
      benefits: [],
      tabs: ['Data'],
    });
  }

  // ---- entertainment and gaming add-ons ----------------------------------
  add({
    rupees: priceFor(55 + Math.floor(random() * 140), 1),
    data: pick(topUpData, random),
    validityDays: 28,
    validity: '28 days',
    calls: 'NA',
    sms: 'NA',
    benefits: ['Prime Video included'],
    tabs: ['Entertainment'],
  });
  add({
    rupees: priceFor(99 + Math.floor(random() * 160), 1),
    data: pick(topUpData, random),
    validityDays: 30,
    validity: '30 days',
    calls: 'NA',
    sms: 'NA',
    benefits: ['Live TV pack'],
    tabs: ['Entertainment', 'Top-up'],
  });
  add({
    rupees: priceFor(111 + Math.floor(random() * 120), 1),
    data: pick(topUpData, random),
    validityDays: 28,
    validity: '28 days',
    calls: 'NA',
    sms: 'NA',
    benefits: ['Gaming pass'],
    tabs: ['Gaming'],
  });
  add({
    rupees: priceFor(399 + Math.floor(random() * 200), 1),
    data: pick(dailyData, random),
    validityDays: 28,
    validity: '28 days',
    calls: 'Unlimited',
    sms: '100/day',
    benefits: ['Gaming pass', 'Unlimited 5G'],
    tabs: ['Gaming', 'Unlimited 5G'],
  });

  // ---- plain talktime ----------------------------------------------------
  for (const amount of [10, 20, 50, 100]) {
    if (plans.length >= PLANS_PER_OPERATOR) break;
    add({
      rupees: priceFor(amount, 1),
      data: 'NA',
      validityDays: null,
      validity: 'Existing plan',
      calls: `₹${(amount * 0.8175).toFixed(2)} talktime`,
      sms: 'NA',
      benefits: [],
      tabs: ['Top-up'],
    });
  }

  // The ladders above are sized to overshoot; trim to exactly forty so every
  // operator's sheet is the same depth.
  while (plans.length < PLANS_PER_OPERATOR) {
    const data = pick(dailyData, random);
    add({
      rupees: priceFor(pick(basePrices, random), 1.4),
      data,
      validityDays: 28,
      validity: '28 days',
      calls: 'Unlimited',
      sms: '100/day',
      benefits: [perks[0] ?? 'Unlimited 5G'],
      tabs: ['Unlimited 5G', 'Popular'],
    });
  }

  return plans.slice(0, PLANS_PER_OPERATOR);
}

/** Every operator's book, keyed by operator id. */
export const PLANS_BY_OPERATOR: Readonly<Record<string, RechargePlan[]>> = Object.fromEntries(
  OPERATORS.map((operator) => [operator.id, generatePlans(operator)]),
);

/** Flat list, for the places that do not care whose plan it is. */
export const RECHARGE_PLANS: readonly RechargePlan[] = OPERATORS.flatMap(
  (operator) => PLANS_BY_OPERATOR[operator.id] ?? [],
);

const PLANS_BY_ID = new Map(RECHARGE_PLANS.map((plan) => [plan.id, plan]));
const OPERATORS_BY_ID = new Map(OPERATORS.map((operator) => [operator.id, operator]));

export function findPlan(id: string): RechargePlan | undefined {
  return PLANS_BY_ID.get(id);
}

export function findOperator(id: string): Operator | undefined {
  return OPERATORS_BY_ID.get(id);
}

export function plansFor(operatorId: string): RechargePlan[] {
  return PLANS_BY_OPERATOR[operatorId] ?? [];
}

export function plansForTab(operatorId: string, tab: PlanTab): RechargePlan[] {
  return plansFor(operatorId)
    .filter((plan) => plan.tabs.includes(tab))
    .sort((a, b) => a.rupees - b.rupees);
}
